{% set name = "validators" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/validators-{{ version }}.tar.gz
  sha256: 002ba1552076535176824e43149c18c06f6b611bc8b597ddbcf8770bcf5f9f5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8

test:
  imports:
    - validators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kvesteri/validators
  summary: Python Data Validation for Humans™
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Python data validation for Humans.

    Python has all kinds of data validation tools, but every one of them seems to require defining a schema or form. I wanted to create a simple validation library where validating a simple value does not require defining a form or a schema.
  doc_url: https://validators.readthedocs.io/
  dev_url: https://github.com/kvesteri/validators

extra:
  recipe-maintainers:
    - brl0
    - xylar
